name: Arch Linux
on:
  push:
    branches: [master]
jobs:
  arch:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update repositories and install essentials
        run: |
          pacman -Syyu --noconfirm
          pacman -S --noconfirm git base-devel sudo xorg-xrandr openssh
          pacman --noconfirm --ask=4 -S iptables-nft

          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder $(pwd)
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_AUR_SSH_KEY }}
      - name: Configure git
        run: |
          sudo -E -u builder env HOME=/home/builder git config --global user.name "Madman10K"
          sudo -E -u builder env HOME=/home/builder git config --global user.email "contact@madladsquad.com"
          sudo -E -u builder env HOME=/home/builder git config --global init.defaultBranch main
          
          sudo -E -u builder env HOME=/home/builder mkdir -p /home/builder/.ssh
          sudo -E -u builder env HOME=/home/builder ssh-keyscan -H aur.archlinux.org >> /home/builder/.ssh/known_hosts
          sudo -E -u builder env HOME=/home/builder chmod -R 600 /home/builder/.ssh/*
      - name: Compile
        run: sudo -E -u builder bash -c "HOME=/home/builder ./run.sh deploy"
