name: Arch Linux
on:
  push:
    branches: [master]
jobs:
  arch:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update repositories and install essentials
        run: |
          pacman -Syyu --noconfirm
          pacman -S --noconfirm git base-devel sudo xorg-xrandr openssh
          pacman --noconfirm --ask=4 -S iptables-nft

          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder $(pwd)
      - name: Configure git
        run: |
          sudo -E -u builder mkdir -p /home/builder/.ssh
          echo "${{ secrets.ACTIONS_AUR_SSH_KEY }}" | sudo -E -u builder tee /home/builder/.ssh/id_rsa > /dev/null
          sudo -E -u builder chmod 600 /home/builder/.ssh/id_rsa
          sudo -E -u builder ssh-keyscan -H aur.archlinux.org | sudo -E -u builder tee -a /home/builder/.ssh/known_hosts > /dev/null
          
          # Start a new SSH agent for builder
          sudo -E -u builder bash -c 'eval $(ssh-agent -s) && ssh-add /home/builder/.ssh/id_rsa && ssh-add -l'

# sudo -E -u builder env HOME=/home/builder chmod -R 600 /home/builder/.ssh/*
      - name: Debug SSH Access
        run: sudo -E -u builder env HOME=/home/builder SSH_AUTH_SOCK=${SSH_AUTH_SOCK} ssh -vvv aur@aur.archlinux.org
      - name: Compile
        run: sudo -E -u builder env HOME=/home/builder ./run.sh deploy
